### ISSUE TITLE
website index.html problem

### ISSUE THREAD

**Issue by james986g** [Mikeexe2/Sasalele-Music-Station#6]
why line 14:
<link rel="stylesheet" type="text/css" href="style.css">

and line 28:
<link rel="stylesheet" href="styles.css"> 

Is the a bug?

**Comment by Mikeexe2** [comment]
@james986g yes, oh my god!!

**Comment by james986g** [comment]
I try to change  line 28: 
                <link rel="stylesheet" href="styles.css">  
to "style.css" but its don't work good problem not solve the only change is website styles.css file gone
